version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=igor
      - RABBITMQ_DEFAULT_PASS=igor
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
  
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    expose:
      - 3000
    ports:
      - 3000:3000

  # app:
  #   container_name: product
  #   build:
  #     context: .
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - MQ_HOST=rabbitmq
  #     - MQ_USERNAME=igor
  #     - MQ_PASSWORD=igor
  #   expose:
  #     - 8080
  #   depends_on:
  #     - rabbitmq
